### ISSUE TITLE
Fails when WITH_INELASTIC=ON: Error: Can't open included file 'fftw3.f03'

### ISSUE THREAD

**Issue by yurivict** [libnegf/libnegf#56]
Version: 1.0.3
OS: FreeBSD 13

**Comment by awvwgk** [comment]
Probably needs to depend on fftw in the Portfile if you include the fftw header. Also, note that the include can still fail due to [gcc#35707](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=35707), *i.e.* make sure to explicitly add the directory with the fftw header via `-I` in the compile options since you can't rely on `CPATH` and the default include directories.

**Comment by yurivict** [comment]
Thank you.
